name: Update Bill Summaries

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggers

jobs:
  update-bills:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Fetch new bills
      env:
        CONGRESS_API_KEY: ${{ secrets.CONGRESS_API_KEY }}
      run: python scripts/fetch_bills.py
        
    - name: Generate summaries
      env:
        HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
      run: python scripts/summarize_bills.py
        
    - name: Generate site
      run: python scripts/generate_site.py
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        commit_message: 'Update bill summaries [skip ci]'
